### ISSUE TITLE
makefile_am_substitution.py is not working

### ISSUE THREAD

**Issue by rishabh900** [Tsar/am2cmake#2]
after running the script nothing appears on the terminal, after keyboard interrupt(ctrl-c) the following appears:-
^CTraceback (most recent call last):
  File "makefile_am_substitution.py", line 81, in <module>
    l = re.findall(r'\$\(\S+?\)', d[var])
  File "/usr/lib/python2.7/re.py", line 181, in findall
    return _compile(pattern, flags).findall(string)
KeyboardInterrupt

**Comment by Tsar** [comment]
I'm very sorry. This repository is too old, I do not remember anything about this script :(
